# Communication and Coordination {#commcoord}

_Contributors: Jade Benjamin-Chung, Ben Arnold_

**These communications guidelines are evolving as we increasingly adopt Slack, but here some general principles if you work closely with Ben.**

## Slack

- If you work with Ben but are not a member of Ben's Slack workspace then ask him to invite you!
- Use Slack for scheduling, coding related questions, quick check ins, etc. If your Slack message exceeds 200 words, it might be time to use email. 

- Use channels instead of direct messages unless you need to discuss something private.

- Include tags on your message (e.g., `@Ben`) when you want to ensure that a person sees the message. Ben doesn't regularly read messages where he isn't tagged.

- Please make an effort to respond to messages that message you (e.g., `@Ben`) as quickly as possible and always within 24 hours, unless of course you are on vacation!

- If you are unusually busy (e.g., taking MCAT/GRE, taking many exams) or on vacation please alert the team in advance so we can expect you not to respond at all / as quickly as usual and also [set your status in Slack](https://get.slack.help/hc/en-us/articles/201864558-Set-your-Slack-status-and-availability) (e.g., it could say "On vacation") so we know not to expect to see you online. 
- Please thread messages in Slack as much as possible. 

## Email

- Use email for longer messages (>200 words) or messages that merit preservation. 
- Generally, strive to respond within 24 hours.  If you are unusually busy or on vacation please alert the team in advance so we can expect you not to respond at all / as quickly as usual. 

## Trello

- Ben manages projects and teams using a [kanban board approach](https://www.atlassian.com/agile/kanban/boards) in [Trello](https://www.trello.com).
- You and/or Ben will add new cards within our team's Trello boards and assign them to team members. 
- Each card represents a discrete chunk of work. 
- Cards higher in a list are higher priority.
- Strive to complete the tasks in your card by the card's due date. Talk to Ben about deadlines -- we can always manage the calendar!
- Use checklists to break down a task into smaller chunks. Usually, you can do this yourself (but ask Ben if you ever want input).
- Move cards to the "DONE" list on a board when they are done. 

## Google Drive

- We mostly use Google Drive to create shared documents with longer descriptions of tasks. These documents are linked to Trello cards. Ben often shares these docs with a whole project team since tasks are overlapping, and even if a task is assigned to one person, others may have valuable insights. 
- Please invite both of Ben's email addresses to any documents you create (bfarnold@gmail.com, ben.arnold@ucsf.edu).

## Calendar / Meetings

- Ben will schedule most meetings through the calendar.
- Our meetings start on the hour. 
- If you are going to be late, please send a message in our Slack channel. 
- If you are regularly not able to come on the hour, notify the team and we might choose the modify the agenda order or the start time.
- Add hoc meetings are welcome. If Ben's office door is open, come in!
